### ISSUE TITLE
hiplot command not working on windows

### ISSUE THREAD

**Issue by saratbhargava** [facebookresearch/hiplot#146]
Hi,

I installed hiplot on windows machine using poetry. I am not able to run the hiplot from command line in my python virtual environment.

```
C:\Users\sarat.chinni\Codes_sequencing\hiplot>hiplot
'hiplot' is not recognized as an internal or external command,
operable program or batch file.
```
I have added .py extension to hiplot function in my virtual environment Scripts folder then I got the following error:

```
C:\Users\sarat.chinni\Codes_sequencing\hiplot>hiplot
Traceback (most recent call last):
  File "C:\Users\sarat.chinni\Codes_sequencing\biobench\sandbox\Sarat\supervised_sequencing\.venv\Scripts\hiplot.py", line 6, in <module>
    sys.exit(hip.run_server_main())
AttributeError: module 'hiplot' has no attribute 'run_server_main'
```
How can I solve this issue on windows? (I am able to install and hiplot in my linux machine and it worked properly)

Thank you

**Comment by danthe3rd** [comment]
Hello @saratbhargava  and thank you for your report 👍

I will investigate what is happening on windows later, but on the meantime you should be able to run hiplot server using `python -m hiplot` as well.
If you have an error like `AttributeError: module 'hiplot' has no attribute XXX`, make sure that you don't have a folder named `hiplot` (or a `hiplot.py` file) as it will be imported rather than the hiplot package you installed.

I hope this helps

**Comment by saratbhargava** [comment]
Thanks a lot, `python -m hiplot` has worked. I think windows doesn't read the hashbang lines to execute it with just `hiplot`.

**Comment by Hirisar** [comment]
Hi !

I have the same issue with Hiplot on Anaconda.
Do you have a workaround about hiplot-render ?

Thanks !

**Comment by danthe3rd** [comment]
Does `hiplot.py` or `hiplot-render.py` work for you?

**Comment by Hirisar** [comment]
`python -m hiplot` runs well because python takes the server in the file `__main__.py`.

Otherwise, there are no files `hiplot.py` and `hiplot-render.py` in the conda package :(

**Comment by danthe3rd** [comment]
I just pushed a new RC version to pip, can you try to install it (`pip install hiplot==0.1.23rc119`) and let me know if `hiplot` and `hiplot-render` work?

**Comment by Hirisar** [comment]
I can't install it.
Do you have the tar.bz2 file for Anaconda ?

Thank you for the time given !

**Comment by danthe3rd** [comment]
Hum right we don't have release-candidate channels for anaconda... It will work on the next release.
In between, you can use the python API as a workaround. To convert `data.csv`, you can do:
```
python -c "import hiplot; hiplot.Experiment.from_csv('data.csv').to_html('rendered.html')"
```

**Comment by danthe3rd** [comment]
This should be fixed in the latest version just released (0.1.23). Let me know if `hiplot` command still doesn't work after the update on windows.

**Comment by Hirisar** [comment]
It doesn't solve my problem.
How do you execute Hiplot and hiplot-render with Anaconda prompt ?
